package edu.stanford.bmir.radx.metadata.validator.lib.evaluators;

public enum EvaluationConstant {
  REQUIRED_FIELD_COUNT,
  RECOMMENDED_FIELD_COUNT,
  OPTIONAL_FIELD_COUNT,
  FILLED_REQUIRED_FILED_COUNT,
  FILLED_RECOMMENDED_FIELD_COUNT,
  FILLED_OPTIONAL_FIELD_COUNT,
  REQUIRED_FIELD_COMPLETENESS,
  RECOMMENDED_FIELD_COMPLETENESS,
  OPTIONAL_FIELD_COMPLETENESS,
  OVERALL_COMPLETENESS;
}
