package edu.stanford.bmir.radx.metadata.validator.lib.evaluators;

public enum EvaluationConstant {
  REQUIRED_FIELD_COUNT,
  RECOMMENDED_FIELD_COUNT,
  OPTIONAL_FIELD_COUNT,
  FILLED_REQUIRED_FIELDS,
  FILLED_RECOMMENDED_FIELDS,
  FILLED_OPTIONAL_FIELDS,
  FILLED_ELEMENTS,
  FILLED_ELEMENTS_COUNT,
  FILLED_REQUIRED_FILEDS_COUNT,
  FILLED_RECOMMENDED_FIELDS_COUNT,
  FILLED_OPTIONAL_FIELDS_COUNT,
  REQUIRED_FIELDS_COMPLETENESS,
  RECOMMENDED_FIELDS_COMPLETENESS,
  OPTIONAL_FIELDS_COMPLETENESS,
  OVERALL_COMPLETENESS,
  FILLED_CONTROLLED_TERMS_COUNT,
  CONTROLLED_TERMS_FREQUENCY,
  ACCESSIBLE_URI_COUNT;
}
