package edu.stanford.bmir.radx.metadata.validator.lib.evaluators;

public enum EvaluationConstant {
  TOTAL_REQUIRED_FIELD,
  TOTAL_RECOMMENDED_FIELD,
  TOTAL_OPTIONAL_FIELD,
  FILLED_REQUIRED_FIELDS,
  FILLED_RECOMMENDED_FIELDS,
  FILLED_OPTIONAL_FIELDS,
  FILLED_ELEMENTS,
  FILLED_ELEMENTS_COUNT,
  FILLED_REQUIRED_FIELDS_COUNT,
  FILLED_RECOMMENDED_FIELDS_COUNT,
  FILLED_OPTIONAL_FIELDS_COUNT,
  REQUIRED_FIELDS_COMPLETION_RATE,
  RECOMMENDED_FIELDS_COMPLETION_RATE,
  OPTIONAL_FIELDS_COMPLETION_RATE,
  ELEMENT_COMPLETION_RATE,
  OVERALL_COMPLETION_RATE,
  FILLED_CONTROLLED_TERMS_COUNT,
  CONTROLLED_TERMS_FREQUENCY,
  ACCESSIBLE_URI_COUNT,
  DUPLICATE_ELEMENT_INSTANCES_COUNT,
  DUPLICATE_ELEMENT_INSTANCES;
}
