package edu.stanford.bmir.radx.metadata.validator.lib;

public enum ValidationName {
  JSON_VALIDATION,
  CEDAR_MODEL_VALIDATION,
  SANITATION_CHECK,
  SCHEMA_VALIDATION,
  REQUIREMENT_VALIDATION,
  ARTIFACT_SCHEMA_VALIDATION,
  DATA_TYPE_VALIDATION,
  CARDINALITY_VALIDATION,
  UNKNOWN
}
